version: "3.8"
services:
  echoer1:
    hostname: echoer1
    image: mendhak/http-https-echo
    environment:
      - HTTP_PORT=7777

  echoer2:
    hostname: echoer2
    image: mendhak/http-https-echo
    environment:
      - HTTP_PORT=8888

  echoer3:
    hostname: echoer3
    image: mendhak/http-https-echo
    environment:
      - HTTP_PORT=9999

  nginx:
    image: nginx
    command: nginx -g "daemon off;"
    volumes:
        - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "80:80"
